### ISSUE TITLE
Add OAuth2 Support

### ISSUE THREAD

**Issue by violaBe** [medizininformatik-initiative/flare#134]
Nicht nur Basic Auth sondern auch Oauth unterstützen, 
für client credentials flow clientId + clientSecret

Beispiel config für `FlareApplication.java` 
```
@Service
public class WebClientService {
 
    private WebClient oauthWebClient;
     
    public WebClientService(WebClient.Builder builder,
                            ReactiveClientRegistrationRepository clientRegistrationRepository,
                            ReactiveOAuth2AuthorizedClientService  authorizedClientService) {
 
        AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager  authorizedClientManager =  new AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(clientRegistrationRepository, authorizedClientService);
        ServerOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
        oauth.setDefaultClientRegistrationId("keycloak");
 
        this.oauthWebClient = builder
                .filter(oauth)
                .baseUrl("http://localhost:8088"/)
                .build();
    }
 
    //.....
}
```

Beispiel config für yml 
```
```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webclient
            scope: test
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: https://my-keycloak.de/auth/realms/my-realm
```

Benötigte dependency
```
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-oauth2-client</artifactId>
</dependency>

```
